# Generated by Django 3.2.8 on 2021-10-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_fllows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fllows',
            new_name='follows',
        ),
    ]
